version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinica-medica 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: notjotape/web-api:v0
    ports:
      - "3333:3333"
    volumes:
      - ./backend-trab-web:/app
      - backend_node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/clinica-medica?schema=public
      - NODE_ENV=development
      - JWT_SECRET=clinica-medica
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
    networks:
      - clinica-medica-network
  
  frontend:
    image: notjotape/web-front:v0
    ports:
      - "3000:3000"
    volumes:
      - ./fron-trab-web:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - clinica-medica-network

volumes:
  postgres_data:
  frontend_node_modules:
  backend_node_modules:

networks:
  clinica-medica-network:
    driver: bridge 