version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinica-medica 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinica-medica-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    image: notjotape/web-api:v0.2
    command: npx prisma migrate deploy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/clinica-medica?schema=public
    depends_on:
      - postgres
    networks:
      - clinica-medica-network

  api:
    image: notjotape/web-api:v0.2
    ports:
      - "3333:3333"
    volumes:
      - backend_node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/clinica-medica?schema=public
      - NODE_ENV=development
      - JWT_SECRET=clinica-medica
    depends_on:
      - postgres
    networks:
      - clinica-medica-network
  
  frontend:
    image: notjotape/web-front:v0.2
    ports:
      - "5173:5173"
    volumes:
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - clinica-medica-network

volumes:
  postgres_data:
  frontend_node_modules:
  backend_node_modules:

networks:
  clinica-medica-network:
    driver: bridge